### ISSUE TITLE
Feature request: Support anstyle crate

### ISSUE THREAD

**Issue by teohhanhui** [mina86/ansi_colours#10]
e.g. impl ColourExt for [`RgbColor`](https://docs.rs/anstyle/latest/anstyle/struct.RgbColor.html) and [`Ansi256Color`](https://docs.rs/anstyle/latest/anstyle/struct.Ansi256Color.html)

**Comment by mina86** [comment]
Does https://github.com/mina86/ansi_colours/tree/a work for you?

**Comment by teohhanhui** [comment]
@mina86 Thanks for working on this. Actually I'm not using `anstyle` myself, but it's what I've come across in my exploration of related crates, and it seems to be the latest contender in the "writing colored output to terminal" space.

(I'm using `palette` though... Not sure if you'd want to support that crate too. Haha... It's not that hard to call the functions in this crate without direct integration: https://github.com/hykilpikonna/hyfetch/pull/317)
