### ISSUE TITLE
Would you consider relicensing?

### ISSUE THREAD

**Issue by sharkdp** [mina86/ansi_colours#4]
When we initially replaced the `bat` source code with the `ansi_colours` dependency (https://github.com/sharkdp/bat/pull/319), I didn't notice that `ansi_colours` was `LGPL3` licensed.

As we statically link against `ansi_colours`, we would need to license `bat` under `LGP3` was well (see https://github.com/sharkdp/bat/issues/792).

Would you consider to license `ansi_colours` under MIT (could be dual license)?

**Comment by sharkdp** [comment]
see https://github.com/sharkdp/bat/issues/792

**Comment by LucaCiucci** [comment]
@mina86 I read [you answer](https://github.com/sharkdp/bat/issues/792#issuecomment-570074671) in sharkdp/bat#792, but I have `ansi_colours` in the dependency tree of a colsed-source app I'm developing and planning to distribute.  
Is there any reason to have LGPL license only for this crate? I can just drop the `ansi_colours` dependency, but I think it would be nice have a second more permissive license.

**Comment by mina86** [comment]
> Is there any reason to have LGPL license only for this crate? 

Yes, the reason is for this crate to remain free software.

**Comment by LucaCiucci** [comment]
But wouldn't it be possible to provide a second license option such as Apache or BSD? I'm just asking, my knowledge is not very good in this field.

**Comment by mina86** [comment]
> But wouldn't it be possible to provide a second license option such as Apache or BSD? I'm just asking, my knowledge is not very good in this field.

No, because then the crate could be included in a closed-source project without providing sources for it.

**Comment by LucaCiucci** [comment]
Understood, thanks for the clarification
